# Generated by Django 5.1.1 on 2024-10-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_channels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_link', models.CharField(max_length=100000)),
            ],
        ),
    ]
