# Generated by Django 5.1.1 on 2024-10-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createchat',
            name='date',
        ),
        migrations.AddField(
            model_name='createchat',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='createchat',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
