# Generated by Django 5.1.1 on 2024-10-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_chatintialize_delete_createchat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatintialize',
            name='emails',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
