# Generated by Django 5.1.1 on 2024-10-07 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0005_alter_chatintialize_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatintialize',
            name='emails',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
    ]
