# Generated by Django 5.1.1 on 2024-10-20 02:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=250)),
                ('another_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('users', models.ManyToManyField(related_name='invited_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
